### ISSUE TITLE
More volume levels & Ability save value

### ISSUE THREAD

**Issue by MadTooth** [averne/MasterVolume#1]
Can you add more volume steps? [3 - 4], I use switch lite :)

**Comment by averne** [comment]
Hi, I didn't think anyone actually used this except me!
Personally I use it to decrease the volume in docked mode so I'd like to keep an easily controllable setting in roughly the [0.5, 0.8] range.
I'm not against your suggestion of course, but I think it needs a bit of consideration. I'll try to see if a logarithmic setting is somewhat sensible, if not I'll need to give it more thought.

**Comment by MadTooth** [comment]
This is very important for all switch lite users

**Comment by MadTooth** [comment]
I estimate that 3 volume levels will be enough, and add the ability to save the value so that after rebooting the system you won’t have to reconfigure AGAIN.

**Comment by averne** [comment]
Implemented with commits and b0ff36831dc35c43b16d17effe2cf2a96c824186 and bf0ac1e0b525ff961773886a6ad1ede06a205520.
New release at: https://github.com/averne/MasterVolume/releases/tag/v1.1.0.
