### ISSUE TITLE
Features: Equalizer and Save settings for each game

### ISSUE THREAD

**Issue by MadTooth** [averne/MasterVolume#3]
**If you don't want to do it, then I don't mind :)**

Can you add features: Equalizer and Save settings for each game ? (maybe this [project](https://github.com/tallbl0nde/TriPlayer)  will help you with an equalizer)

**Comment by averne** [comment]
Equalizer is straight up not possible.
Per-game settings would need a sysmodule too, which I consider out of scope as mentionned in your previous request.
