### ISSUE TITLE
More volume levels

### ISSUE THREAD

**Issue by JinsimeuroGamsadeurimnida** [averne/MasterVolume#4]
Hi,

I just found this overlay thanks to someone from some Discord server. Would it be possible to increase the max volume even more? You literally made Tony Hawk's Pro Skater 1+2 playable and I'm not exaggerating. Who on earth releases a game with a fantastic soundtrack that you can barely hear? It just screams to turn it up. I'm on Switch OLED and it still could be a tad louder, like 1-2 levels?

Thank you **SO much** for this! Can't believe that I found it just now.

**Comment by averne** [comment]
I increased the maximum gain to x8.
https://github.com/averne/MasterVolume/releases/tag/v1.1.1
