### ISSUE TITLE
Toggle speakers in docked mode

### ISSUE THREAD

**Issue by Inclsevd** [averne/MasterVolume#5]
Hello,

Would you consider adding the functionality to toggle the use of the Switch tablet speakers whilst in docked mode to your overlay? I found a homebrew for this and immediately thought it would be so much more convenient as an overlay and that it would synergize very well with MasterVolume, without the need for another overlay bloating the list.  The homebrew in question is here: https://github.com/paulocode/switch_internal_speakers_nro

Thanks

**Comment by averne** [comment]
Implemented in https://github.com/averne/MasterVolume/commit/a755e4a0426d8aa0ad12c8d45a82f40757758dde.
https://github.com/averne/MasterVolume/releases/tag/v1.2.0
